### PR TITLE
Add a "Try it online" page

### PR DESCRIPTION
**Pull request by bertfrees**
Unfortunately this doesn't work on Safari, Chrome or Opera. Haven't tested with IE. Reiner's page has got the same issue by the way.

### CODE REVIEW

**Review by egli — APPROVED** [review]
This sure is a lot of code. Where did you get that? Is that from Reiner?

**Comment by bertfrees** [comment]
The code is mostly mine. liblouis.js/liblouis-worker.js is a based a bit on Reiner's code. liblouis-easy-api.js was taken from https://github.com/liblouis/liblouis-js.

**Comment by bertfrees** [comment]
@egli Did you have a chance to try it out?

**Comment by egli** [comment]
No I didn't

**Comment by bertfrees** [comment]
@egli Reminder.

**Comment by bertfrees** [comment]
@egli Friendly reminder.

**Comment by egli** [comment]
OK, I tried it: it gives me a page where I can edit some text but it doesn't seem to translate. Don't know if it doesn't find the tables or what the problem is.

For Danish uncontracted 6dot:
```
abcdefg
```
---
```
⠢⠢⠢⠢⠢⠢⠢
```
For Danish computer:
```
a
```
---
```
⠈⡳⠭⠴⠴⠖⠂⠈
```

**Comment by bertfrees** [comment]
Which browser?

**Comment by bertfrees** [comment]
I tested it again, with Firefox. Apparently things broke for Firefox too. A while back it still worked. The issue is with `include` rules which don't work so the tables are not loaded correctly unless everything is in a single table (but that's hardly ever the case ofc).

**Comment by egli** [comment]
> Which browser?

Tried both FireFox and Chromium

**Comment by bertfrees** [comment]
> The issue is with `include` rules which don't work

I found out that was not the problem after all. The problem was that when loading tables from https://raw.githubusercontent.com (with ` FS.createLazyFile`), the tables are truncated. I fixed it by publishing the JS files and the tables to http://liblouis.org/js-build/.

**Comment by bertfrees** [comment]
The only problem now is that [cfb716](https://github.com/liblouis/liblouis/commit/cfb716) is the latest Liblouis revision for which a JS build exists. The "emscriptem" workflow stopped working and we eventually disabled it.

**Comment by bertfrees** [comment]
A related issue is that we decided to not publish to the js-build repo anymore when we [moved from Travis to GH Actions](https://github.com/liblouis/liblouis/pull/1039). Instead we upload build-no-tables-utf32.js to the ["snapshot" release](https://github.com/liblouis/liblouis/releases/tag/snapshot). I guess this is still fine, but then the latest tables should be somehow published somewhere. (Alternatively, we publish the version of the JS build with the tables included, but it's 46.2 MB.)

**Comment by bertfrees** [comment]
> The "emscriptem" workflow stopped working and we eventually disabled it.

> A related issue is that we decided to not publish to the js-build repo anymore when we https://github.com/liblouis/liblouis/pull/1039.

I've fixed these things in https://github.com/liblouis/liblouis/pull/1205

**Comment by bertfrees** [comment]
I added a preview of the page so we can have it tested by some people and have it checked for accessibility: http://liblouis.org/translate/. Note that I haven't updated the navigation bar so the page should be invisible for people that don't have the link.

**Review by egli — APPROVED** [review]
I didn't really review the javascript code. Where did you get this code? I looked at the page and it works like a charm. Thanks a lot!

**Comment by bertfrees** [comment]
I wrote part of it and part of it is from Reiner. See https://github.com/liblouis/liblouis.github.io/pull/7#issuecomment-697496668.

**Comment by bertfrees** [comment]
Rebased and merged

**Comment by egli** [comment]
Man, this stuff is totally cool! I didn't realize you get to see the contractions when you put the cursor on it.

I think this definitely deserves a news entry on the web page and a post to the mailing list.

Oh, before I brag too much about it, can a blind person see the highlighted contractions? Probably not.

**Comment by bertfrees** [comment]
Thanks :-)

I also doubt a blind person can see the highlighting. I have no idea whether that is possible and how it could be done.

**Pull request merged**
