### PR TITLE
Add a sponsoring page

### PR DESCRIPTION
**Pull request by egli**

### CODE REVIEW

**Review by bertfrees — APPROVED** [review]
Thanks!

**Comment by bertfrees** [comment]
What about also putting a Make a donation button somewhere prominent on the front page (or better, on every page)?

Not sure exactly where to put it, I've tried some things, for example:

Screenshot 2020-03-20 at 15 42 20

**Comment by egli** [comment]
I added a link in the menu to the Sponsoring page. We can add a button if you like. Just maybe do not use an image from paypal

**Comment by bertfrees** [comment]
Yes I can see the link in the menu but a button makes it more visible. I think the image from Paypal is very recognizable because used in many places. But maybe people will expect that they will be redirected to Paypal.

What about the placing?

**Pull request merged**
